# Generated by Django 5.2.4 on 2025-08-01 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Email',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Adress',
        ),
    ]
